### ISSUE TITLE
Wiki or sample?

### ISSUE THREAD

**Issue by matheusjardimb** [MateusZitelli/mundipagg-smartwallet-python#1]
Hello there, great job.

It seems the official app still doesn't implement smartwallet... What should I do in order to integrate your lib?

Would it be possible to post an example or wiki page?

**Comment by MateusZitelli** [comment]
Hey @matheusjardimb, just added some basic examples in a README, if you have any questions I'm glad to help you.

**Comment by matheusjardimb** [comment]
tks a lot! I'll check it out
